services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: PLAYBEACH_ADM
      POSTGRES_PASSWORD: PLAYBEACH_ADM
      POSTGRES_DB: PDBPLAYBEACH
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U PLAYBEACH_ADM -d PDBPLAYBEACH" ]
      interval: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playbeach_api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: