services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: PLAYBEACH_ADM
      POSTGRES_PASSWORD: PLAYBEACH_ADM
      POSTGRES_DB: PDBPLAYBEACH
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: